kind: Service
apiVersion: v1
metadata:
  name: {{ template "openvpn.fullname" . }}
  labels:
    app: {{ template "openvpn.name" . }}
    chart: {{ template "openvpn.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
  ports:
    - name: openvpn-udp
      targetPort: {{ .Values.service.internalPort }}
      protocol: UDP
      port: {{ (add .Values.vpn.server_port 0) }}
      nodePort: {{ (add .Values.vpn.server_port 0) }}
    - name: openvpn-tcp
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      port: {{ (add .Values.vpn.server_port 0) }}
      nodePort: {{ (add .Values.vpn.server_port 0) }}
    - name: pfwd1-udp
      targetPort: 9901
      protocol: UDP
      port: {{ (add .Values.vpn.server_port 1) }}
      nodePort: {{ (add .Values.vpn.server_port 1) }}
    - name: pfwd1-tcp
      targetPort: 9901
      protocol: TCP
      port: {{ (add .Values.vpn.server_port 1) }}
      nodePort: {{ (add .Values.vpn.server_port 1) }}
    - name: pfwd2-udp
      targetPort: 9902
      protocol: UDP
      port: {{ (add .Values.vpn.server_port 2) }}
      nodePort: {{ (add .Values.vpn.server_port 2) }}
    - name: pfwd2-tcp
      targetPort: 9902
      protocol: TCP
      port: {{ (add .Values.vpn.server_port 2) }}
      nodePort: {{ (add .Values.vpn.server_port 2) }}
    - name: pfwd3-udp
      targetPort: 9903
      protocol: UDP
      port: {{ (add .Values.vpn.server_port 3) }}
      nodePort: {{ (add .Values.vpn.server_port 3) }}
    - name: pfwd3-tcp
      targetPort: 9903
      protocol: TCP
      port: {{ (add .Values.vpn.server_port 3) }}
      nodePort: {{ (add .Values.vpn.server_port 3) }}
    - name: pfwd4-udp
      targetPort: 9904
      protocol: UDP
      port: {{ (add .Values.vpn.server_port 4) }}
      nodePort: {{ (add .Values.vpn.server_port 4) }}
    - name: pfwd4-tcp
      targetPort: 9904
      protocol: TCP
      port: {{ (add .Values.vpn.server_port 4) }}
      nodePort: {{ (add .Values.vpn.server_port 4) }}
    - name: pfwd5-udp
      targetPort: 9905
      protocol: UDP
      port: {{ (add .Values.vpn.server_port 5) }}
      nodePort: {{ (add .Values.vpn.server_port 5) }}
    - name: pfwd5-tcp
      targetPort: 9905
      protocol: TCP
      port: {{ (add .Values.vpn.server_port 5) }}
      nodePort: {{ (add .Values.vpn.server_port 5) }}
    - name: pfwd6-udp
      targetPort: 9906
      protocol: UDP
      port: {{ (add .Values.vpn.server_port 6) }}
      nodePort: {{ (add .Values.vpn.server_port 6) }}
    - name: pfwd6-tcp
      targetPort: 9906
      protocol: TCP
      port: {{ (add .Values.vpn.server_port 6) }}
      nodePort: {{ (add .Values.vpn.server_port 6) }}
    - name: pfwd7-udp
      targetPort: 9907
      protocol: UDP
      port: {{ (add .Values.vpn.server_port 7) }}
      nodePort: {{ (add .Values.vpn.server_port 7) }}
    - name: pfwd7-tcp
      targetPort: 9907
      protocol: TCP
      port: {{ (add .Values.vpn.server_port 7) }}
      nodePort: {{ (add .Values.vpn.server_port 7) }}
    - name: pfwd8-udp
      targetPort: 9908
      protocol: UDP
      port: {{ (add .Values.vpn.server_port 8) }}
      nodePort: {{ (add .Values.vpn.server_port 8) }}
    - name: pfwd8-tcp
      targetPort: 9908
      protocol: TCP
      port: {{ (add .Values.vpn.server_port 8) }}
      nodePort: {{ (add .Values.vpn.server_port 8) }}
    - name: pfwd9-udp
      targetPort: 9909
      protocol: UDP
      port: {{ (add .Values.vpn.server_port 9) }}
      nodePort: {{ (add .Values.vpn.server_port 9) }}
    - name: pfwd9-tcp
      targetPort: 9909
      protocol: TCP
      port: {{ (add .Values.vpn.server_port 9) }}
      nodePort: {{ (add .Values.vpn.server_port 9) }}
  selector:
    app: {{ template "openvpn.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
