kind: Service
apiVersion: v1
metadata:
  name: {{ template "openvpn.fullname" . }}
  labels:
    app: {{ template "openvpn.name" . }}
    chart: {{ template "openvpn.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
  ports:
    - name: openvpn-udp
      targetPort: {{ .Values.service.internalPort }}
      protocol: UDP
      port: {{ (add .Values.service.portOffset 0) }}
      nodePort: {{ (add .Values.service.portOffset 0) }}
    - name: openvpn-tcp
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      port: {{ (add .Values.service.portOffset 0) }}
      nodePort: {{ (add .Values.service.portOffset 0) }}
    - name: pfwd1-udp
      targetPort: 9901
      protocol: UDP
      port: {{ (add .Values.service.portOffset 1) }}
      nodePort: {{ (add .Values.service.portOffset 1) }}
    - name: pfwd1-tcp
      targetPort: 9901
      protocol: TCP
      port: {{ (add .Values.service.portOffset 1) }}
      nodePort: {{ (add .Values.service.portOffset 1) }}
    - name: pfwd2-udp
      targetPort: 9902
      protocol: UDP
      port: {{ (add .Values.service.portOffset 2) }}
      nodePort: {{ (add .Values.service.portOffset 2) }}
    - name: pfwd2-tcp
      targetPort: 9902
      protocol: TCP
      port: {{ (add .Values.service.portOffset 2) }}
      nodePort: {{ (add .Values.service.portOffset 2) }}
    - name: pfwd3-udp
      targetPort: 9903
      protocol: UDP
      port: {{ (add .Values.service.portOffset 3) }}
      nodePort: {{ (add .Values.service.portOffset 3) }}
    - name: pfwd3-tcp
      targetPort: 9903
      protocol: TCP
      port: {{ (add .Values.service.portOffset 3) }}
      nodePort: {{ (add .Values.service.portOffset 3) }}
  selector:
    app: {{ template "openvpn.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
