kind: Service
apiVersion: v1
metadata:
  name: {{ template "openvpn.fullname" . }}
  labels:
    app: {{ template "openvpn.name" . }}
    chart: {{ template "openvpn.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
  ports:
    - name: openvpn
      port: {{ .Values.service.portOffset | &0 }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: {{ .Values.openvpn.OVPN_PROTO | upper }}
    - name: forward1_tcp
      port: {{ .Values.service.portOffset | &1 }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
    - name: forward1_udp
      port: {{ .Values.service.portOffset | &1 }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: UDP
    - name: forward2_tcp
      port: {{ .Values.service.portOffset | &2 }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
    - name: forward2_udp
      port: {{ .Values.service.portOffset | &2 }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: UDP
    - name: forward3_tcp
      port: {{ .Values.service.portOffset | &3 }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
    - name: forward3_udp
      port: {{ .Values.service.portOffset | &3 }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: UDP
  selector:
    app: {{ template "openvpn.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
