kind: Service
apiVersion: v1
metadata:
  name: {{ template "openvpn.fullname" . }}
  labels:
    app: {{ template "openvpn.name" . }}
    chart: {{ template "openvpn.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
  ports:
    - name: openvpn
      port: {{ (add .Values.service.portOffset 0) }} 
      targetPort: 1194 
      protocol: UDP
    - name: svc1-udp
      port: {{ (add .Values.service.portOffset 1) }} 
      targetPort: 9901
      protocol: UDP
  selector:
    app: {{ template "openvpn.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
