# Default values for openvpn.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

updateStrategy: {}
  # type: RollingUpdate
  # rollingUpdate:
  #   maxSurge: 1
  #   maxUnavailable: 0

image:
  repository: jfelten/openvpn-docker
  tag: 1.1.0
  pullPolicy: IfNotPresent
service:
  type: NodePort
  internalPort: 1194
  externalIPs: []

  ## Here annotations can be added to the openvpn service
  # annotations:
  #   external-dns.alpha.kubernetes.io/hostname: vpn.example.com
  annotations: {}

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 25m
    memory: 64Mi

general:
  service_id: undefined  

vpn:
  # Server address for the client.
  server_address: 0.0.0.0
  # Server port for the client.
  server_port: 0
  # Protocol used for connection. tcp or udp (default: udp).
  connection_protocol: udp
  # Network used for openvpn clients.
  tunnel_network: 172.30.30.0
  # Network mask used for openvpn client.
  tunnel_mask: 255.255.255.0
  # Tunnel IPs
  tunnel_server_ip: 172.30.30.1
  tunnel_client_ip: 172.30.30.2
  # Arbitrary lines appended to the end of the server configuration file
  # conf: |
  #  max-clients 100
  #  client-to-client

client: 
  # Network behind the client
  network_ip: 192.168.1.0
  # Network Mask behind the client
  network_mask: 255.255.255.0


forwarding:
  pf1:
    destination: 127.0.0.1
    port: 8999
  pf2:
    destination: 127.0.0.1
    port: 8999
  pf3:
    destination: 127.0.0.1
    port: 8999