# Default values for openvpn.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

updateStrategy: {}
  # type: RollingUpdate
  # rollingUpdate:
  #   maxSurge: 1
  #   maxUnavailable: 0

image:
  repository: jfelten/openvpn-docker
  tag: 1.1.0
  pullPolicy: IfNotPresent
service:
  type: NodePort
  internalPort: 1194
  externalIPs: []
  portOffset: 0


  ## Here annotations can be added to the openvpn service
  # annotations:
  #   external-dns.alpha.kubernetes.io/hostname: vpn.example.com
  annotations: {}

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 25m
    memory: 64Mi

openvpn:
  # Network allocated for openvpn clients (default: 10.240.0.0).
  OVPN_NETWORK: 172.30.30.0
  # Network subnet allocated for openvpn client (default: 255.255.0.0).
  OVPN_SUBNET: 255.255.255.0
  # Protocol used by openvpn tcp or udp (default: udp).
  OVPN_PROTO: tcp
  # Kubernetes pod network (optional).
  OVPN_K8S_POD_NETWORK: ""
  # Kubernetes pod network subnet (optional).
  OVPN_K8S_POD_SUBNET: ""
  # Push a `dhcp-option DOMAIN` config
  dhcpOptionDomain: false
  # Redirect all client traffic through VPN
  redirectGateway: false
  # Arbitrary lines appended to the end of the server configuration file
  # conf: |
  #  max-clients 100
  #  client-to-client
  route: 
    ip: 192.168.1.0
    mask: 255.255.255.0

routing:
  pf1:
    destination: 127.0.0.1
    port: 8999
  pf2:
    destination: 127.0.0.1
    port: 8999
  pf3:
    destination: 127.0.0.1
    port: 8999